import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar/NavBar";
import Footer from "@/components/Footer/Footer";
import FixedActions from "@/components/FixedActions/FixedActions";
import Providers from "./Providers";

const inter = Inter({ subsets: ["latin"], display: "swap" });

export const metadata = {
  title: "Elba Catalini",
  description: "This is an eccomerce application generated by next js",
  author: "Juan Ignacio Colli",
  keywords: "nextjs, react, web application",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },
  manifest: "/site.webmanifest",
  openGraph: {
    title: "Elba Catalini - Tienda Online",
    description: "Compra productos Baiml y mucho mas al mejor precio!.",
    url: "https://tudominio.com",
    siteName: "Elba Catalini",
    images: [
      {
        url: "/og-image.jpg",
        width: 1200,
        height: 630,
      },
    ],
    type: "website",
  },
  /* charset: "UTF-8",
  ogTitle: "Tu Aplicación Next.js",
  ogDescription: "Descripción de tu aplicación Next.js para redes sociales",
  ogImage: "/path/to/your/image.jpg",
  ogUrl: "https://la-casa-del-accesorio-production.up.railway.app/",
  twitterCard: "summary_large_image",
  twitterCreator: "@tuTwitterHandle", */
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NavBar />
          {children}
          <FixedActions />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
