import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar/NavBar";
import Footer from "@/components/Footer/Footer"
import Providers from "./Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "La Casa del Accesorio",
  description: "This is an eccomerce application generated by next js",
  author: "Juan Ignacio Colli",
  keywords: "nextjs, react, web application",
  icons: {
    icon: "/favicon.ico",
  },
  /* charset: "UTF-8",
  ogTitle: "Tu Aplicación Next.js",
  ogDescription: "Descripción de tu aplicación Next.js para redes sociales",
  ogImage: "/path/to/your/image.jpg",
  ogUrl: "https://la-casa-del-accesorio-production.up.railway.app/",
  twitterCard: "summary_large_image",
  twitterCreator: "@tuTwitterHandle", */
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NavBar />
          {children}
          <Footer/>
        </Providers>
      </body>
    </html>
  );
}
